
%% =====================================================================%%
% It function execute several script written in python which allow
% simulate a netlist using the Spectre simulador, it script return in the 
% same PATH of the netlist the file that correspond to signals sorted
% by the Clumnas ASCII format, that could be read by Matlab. The user can 
% specifiy the signals that want to plot, upon 2 signals at same time.
% The algortihm also create one folder with the name specified by the user
% so, the result can be found in that folder. The results is both in .png 
% as .fig format to an easy reading.
%% =====================================================================%%

clear all
close all
clc

%% ============== Here must be the scripts of python ===================%%
% In it path must be the netlist 
PATH = '/home/netware/users/jpgironruiz/Documents/Cadence_analysis/';
cd(PATH)

%% ==================== generates the signals ========================= %%

number_pixel = 1;

nameinput = input ...
    ('Write the name of the input signal without extension e.g. signal ');

%called to the function to generates the input signal

eventsPerPeriod = 1000;
factor_current = 100e-12;
period_Signal = 1e-3;

signal_sweep_illuminance(number_pixel,nameinput, ...
                eventsPerPeriod,period_Signal,factor_current)
            
path_DIR_input = strcat(PATH,nameinput,'/');

%% ===================== CALL TO SCRIPTS  ==============================%%

nameNetlist_spectre = input ...
    ('Write the name of the netlist generated by Spectre with extension .scs ');
nameNetlist_output = input ...
    ('Write the name of the output netlist without extension:  ');

ext_input = input...
    ('Write the extension of the input signal e.g.  .csv');


%% Here is changed the netlist by intuitives names 
command = ['python' ' ' 'setting_input_netlist_UNIX.py' ' ' PATH ' ' ...
    path_DIR_input ' ' nameNetlist_spectre ' ' nameNetlist_output ' '...
    nameinput ' ' ext_input ' ' int2str(number_pixel)]

system(command)
%% here is executed the spectre simulator
name_output_simulation = input('Write the name of the output simulation with extension: ');
command = ['python' ' ' 'executing_spectre_command_UNIX.py' ' ' PATH ' ' ...
    nameNetlist_output ' ' name_output_simulation]
system(command)
%% Here is plotted the signals

%signals_simulation = importdata(name_output_simulation);
%signals = signals_simulation(1,:)

%time = signals_simulation(:,1);
%C_ON_ACK = output_spectre(:,10);
%V_pd = output_spectre(:,3);
%I_pd = output_spectre(:,2);
%figure
%[ax,h1,h2] = plotyy(time,I_pd,time,C_ON_ACK,'plot','plot');

