#!/bin/bash

#It script allow execute the Matlab Function "processing_spectre_out"

# Reading user input


echo -n "Write the name of the simulation"
read name_simulation

echo -n "Write the name of the netlist generated by Spectre with extension .scs"
read nameNetlist_spectre



nohup matlab -nodesktop -nosplash -r "test "$name_simulation" "$nameNetlist_spectre"" #> ../../Simulation_cameras/$name_simulation/output_matlab.out


