#!/bin/bash

#It script allow execute the Matlab Function "processing_spectre_out"

# Reading user input


echo -n "Write the name of the simulation "
read name_simulation

echo -n "Write the name of the netlist generated by Spectre with extension .scs "
read nameNetlist_spectre

# Creating the folder to the simulation
PATH_scriptMatlab=$PWD/

cd $PATH_scriptMatlab
cd ..
PATH_script=$PWD/
PATH_scriptPython=$PATH_script"python"/
cd ..

############################################################
namefolder_netlistSpectre="Netlist_Spectre"
mkdir $namefolder_netlistSpectre
PATH_netlist_spectre=$PWD/$namefolder_netlistSpectre/

namefolder_simulation="Simulation_cameras"
mkdir $namefolder_simulation



PATH_simulation=$PWD/$namefolder_simulation/
cd $PATH_simulation
############################################################

############### CREATING THE DIRECTORIES   #########
mkdir $name_simulation

# Guarantee that the simulation have a unique name
while [ $? -ne 0 ]; do
  
  echo " The directory exist"
  echo " Do you want re-write it? [y/n]"
  read answer
  
  while [ $answer != "y" ] && [ $answer != "n" ]
  do 
    echo "I dont understand write y or n"
    read answer
  done
  
  if [ $answer == "y" ] ; then
    
    rm -rf $name_simulation
    mkdir $name_simulation
  else
    echo "Write other name different to the first"
    read name_simulation
    mkdir $name_simulation
  fi
done


PATH_folder_simulation=$PATH_simulation$name_simulation/
cd $PATH_folder_simulation

nameinput="input_"$name_simulation
name_folder_matlab_output="output_matlab_"$name_simulation
name_matlab_output="output_matlab_"$name_simulation".csv"
name_images="images_"$name_simulation
name_folder_nohup="nohup_"$name_simulation

mkdir $nameinput
mkdir $name_folder_matlab_output
mkdir $name_images
mkdir $name_folder_nohup

PATH_sim_output_matlab=$PATH_folder_simulation$name_folder_matlab_output/
PATH_folder_input=$PATH_folder_simulation$nameinput/
PATH_folder_images=$PATH_folder_simulation$name_images/
PATH_folder_nohup=$PATH_folder_simulation$name_folder_nohup/

cd $PATH_scriptMatlab

###################### EXPORTING THE PATHS ###############


export PATH_scriptMatlab
export PATH_script
export PATH_scriptPython
export PATH_netlist_spectre
export PATH_simulation
export PATH_folder_simulation
export PATH_sim_output_matlab
export PATH_folder_input
export PATH_folder_images
export PATH_folder_nohup
export nameinput
export name_folder_matlab_output
export name_matlab_output
export name_images
export name_folder_nohup


nohup matlab -nodesktop -nosplash -r "simulation_spectre_pixel_UNIX "$name_simulation" "$nameNetlist_spectre"" > "output_matlab_"$name_simulation".out" & export PID_SIM=$! 
#mv output_matlab ../../Simulation_cameras/$name_simulation/"nohup_"$name_simulation/ 


